### ISSUE TITLE
authen下面的GetRedirectUri里应该是redirect_uri不是redirectUri

### ISSUE THREAD

**Issue by NoUltimate** [fastwego/feishu#1]
![image](https://user-images.githubusercontent.com/32738861/90863739-2e68c480-e3c2-11ea-94e2-86ab798c1ded.png)
![image](https://user-images.githubusercontent.com/32738861/90863885-548e6480-e3c2-11ea-98bf-03f2d404f19b.png)

**Comment by Ceelog** [comment]
sorry ，接口太多，眼睛花了，你发个 pull request ? 我合并更新一下

**Comment by NoUltimate** [comment]
没事，我自己提的位置也没描述的很清楚，我提了你看下改的对不对

**Comment by Ceelog** [comment]
Well Done
